# -*- coding: utf-8 -*-
W = 'webapp/src/main/webapp/'
V = W + 'WEB-INF/views/'
G = W + 'WEB-INF/tags/'
R = 'webapp/src/main/resources/'
M = 'persistence/src/main/resources/db/migration/'
H = {
 'README.md': 'Instalación, configuración y funcionalidades. Ojo: la sección de credenciales describe el registro anterior.',
 'CONTEXT.md': 'Glosario del dominio y palabras a evitar. Leelo entero: es corto y fija el vocabulario.',
 'CLAUDE.md': 'Reglas del equipo por capa. La mejor síntesis de las convenciones.',
 'AGENTS.md': 'Mismo contenido que CLAUDE.md, para otros agentes.',
 'docs/setup.md': 'Tecnologías, comandos y reglas de dependencias.',
 'TODO.md': 'Pendientes al 9 de septiembre. Casi todo está resuelto: leelo como historia.',
 'docs/adr/0001-establish-quiero-vinilos-domain.md': 'Por qué el producto es quieroVinilos.',
 'docs/adr/0002-own-the-album-catalog-locally.md': 'Por qué el catálogo de álbumes es propio.',
 'docs/adr/0003-conversation-inside-the-inquiry.md': 'Por qué la conversación vive dentro de la consulta.',
 'pom.xml': 'Módulos, versiones en propiedades, dependencyManagement y plugin de Jetty.',
 'models/pom.xml': 'Sin dependencias del proyecto.',
 'persistence-contracts/pom.xml': 'Solo depende de models.',
 'persistence/pom.xml': 'Spring JDBC y driver; HSQLDB y Flyway en test.',
 'services-contracts/pom.xml': 'Solo depende de models.',
 'services/pom.xml': 'Mirá el scope runtime de persistence.',
 'webapp/pom.xml': 'Dependencias runtime, nombre del WAR, exclusión de logback-test y perfil pampero.',
 'models/src/main/resources/.gitkeep': 'Archivo vacío para conservar el directorio.',
 W + 'WEB-INF/web.xml': 'Listeners, filtros en orden, DispatcherServlet, sesión por cookie y página de 404.',
 R + 'database.properties.example': 'Keys de conexión a la base.',
 R + 'mail.properties.example': 'Keys de SMTP, timeouts, remitente y URL base.',
 'webapp/src/pampero/resources/database.properties.example': 'Lo mismo para el servidor de la cátedra.',
 'webapp/src/pampero/resources/mail.properties.example': 'Lo mismo para el servidor; mirá la URL base con context path.',
 R + 'logback.xml': 'Dos archivos diarios; leé el comentario sobre el nombre.',
 R + 'logback-test.xml': 'Consola en DEBUG para desarrollo.',
 '.gitignore': 'Qué no se versiona: compilados y propiedades con credenciales.',
 '.worktreeinclude': 'Propiedades que se copian a un worktree nuevo.',
 M + 'V1__esquema_inicial.sql': 'Tablas base. Leé los comentarios del encabezado y el de inquiries.',
 M + 'V2__email_unico_en_users.sql': 'Unicidad del correo.',
 M + 'V3__fks_de_posts_y_albums.sql': 'Claves foráneas que faltaban.',
 M + 'V4__titulo_normalizado_en_albums.sql': 'Identidad del álbum sin índice sobre expresión.',
 M + 'V5__venta_con_comprobante.sql': 'La más grande: cobro, direcciones, reserva, comprobante, precio, estados.',
 M + 'V6__cuenta_verificada.sql': 'enabled pasa a verified; fecha en los tokens.',
 M + 'V7__mensajes_de_consulta.sql': 'Mensajes; la única que mueve datos.',
 M + 'V8__post_gallery.sql': 'Fotos adicionales, tope y orden.',
 M + 'V9__user_avatars.sql': 'Foto de perfil.',
 M + 'V10__sale_reviews.sql': 'Reseñas con sus tres restricciones.',
 M + 'V11__carrito.sql': 'Carrito con clave compuesta y cascada.',
 'persistence/src/test/resources/populator.sql': 'Datos fijos de los tests de DAO. Ubicá qué cuenta, post y consulta representa cada caso.',
 'tools/setup_local_postgres.sh': 'Guía interactiva para preparar PostgreSQL local.',
 'tools/seed_local_data.sh': 'Carga el catálogo de demostración en una transacción.',
 'database/seed_dev_posts.sql': 'SQL del catálogo de demostración.',
 'database/demo_posts.tsv': 'Las publicaciones de demostración.',
 'tools/sql/demo-users.sql': 'Dos cuentas de demostración.',
 'database/users.sql': 'Resto del esqueleto inicial; no se usa.',
 V + 'landing/index.jsp': 'Filtros, orden, grilla, estado vacío y paginación.',
 G + 'vinyl-card.tag': 'La tarjeta de un vinilo; el componente más reutilizado.',
 G + 'pagination.tag': 'Flechas que conservan parámetros y ancla.',
 G + 'pagination-link.tag': 'Un enlace de página.',
 G + 'post-badge.tag': 'Estado de una publicación.',
 W + 'js/catalog.js': 'Envía el orden al cambiar el select; pliega filtros en pantallas angostas.',
 W + 'js/autocomplete.js': 'Sugerencias: espera, número de secuencia, JSON y nodos armados con textContent.',
 V + 'auth/register.jsp': 'Formulario de registro.',
 V + 'auth/login.jsp': 'Login: mirá los nombres de los campos y el token CSRF.',
 V + 'auth/verify.jsp': 'Resultado de abrir el enlace de verificación.',
 V + 'auth/verify-required.jsp': 'Pantalla para la cuenta sin verificar.',
 V + 'auth/forgot-password.jsp': 'Pedido de recuperación.',
 V + 'auth/reset-password.jsp': 'Nueva contraseña con el token en un campo oculto.',
 G + 'resend-verification.tag': 'Botón de reenvío: POST con CSRF.',
 V + 'publish/index.jsp': 'Publicar y editar comparten vista.',
 W + 'js/publish-preview.js': 'Vista previa de la tarjeta mientras se completa el formulario.',
 W + 'images/covers/placeholder.svg': 'Tapa por defecto.',
 V + 'post/detail.jsp': 'Ficha: galería, vendedor, acciones según quién mira.',
 W + 'js/post-gallery.js': 'Cambia la foto principal al tocar una miniatura.',
 W + 'js/sale-detail.js': 'Página de la venta: alto de la conversación, scroll al último mensaje, Enter para enviar y cancelar la edición de la reseña.',
 V + 'post/contact.jsp': 'Mensaje y elección de dirección.',
 G + 'address-fields.tag': 'Campos de una dirección.',
 G + 'address.tag': 'Muestra una dirección, completa o recortada.',
 V + 'inquiry/received.jsp': 'Bandeja del vendedor, agrupada por publicación.',
 V + 'inquiry/sent.jsp': 'Bandeja del comprador.',
 V + 'inquiry/detail.jsp': 'La página de la venta: acciones según estado y rol, conversación, reseña.',
 G + 'inquiry-nav.tag': 'Pestañas recibidas y enviadas.',
 G + 'inquiry-status.tag': 'Estado de la consulta como texto.',
 G + 'inbox-group-header.tag': 'Cabecera de un grupo de la bandeja: miniatura, título y estado. Elige la URL de la tapa según exista o no el post.',
 G + 'inbox-last-message.tag': 'Último mensaje de la conversación.',
 G + 'confirm-dialog.tag': 'Diálogo de confirmación.',
 W + 'js/confirm-action.js': 'Abre el diálogo antes de enviar un formulario destructivo.',
 W + 'js/submit-once.js': 'Evita el doble envío.',
 G + 'star-rating-input.tag': 'Estrellas como radios accesibles.',
 G + 'rating.tag': 'Estrellas de solo lectura con relleno parcial para promedios.',
 G + 'review-content.tag': 'Puntaje, comentario y, opcional, autor de una reseña.',
 G + 'user-byline.tag': 'Foto y nombre de una Cuenta con enlace a su perfil público.',
 G + 'filter-chips.tag': 'Chips de filtro con su cantidad; el chip activo lleva a la URL sin filtro.',
 V + 'profile/index.jsp': 'Perfil privado: cuenta, contraseña, cobro, direcciones, publicaciones.',
 G + 'account-nav.tag': 'Menú de la cuenta en la cabecera.',
 G + 'avatar.tag': 'Foto o inicial.',
 W + 'js/account-edit.js': 'Filas editables del perfil y diálogo de la foto.',
 V + 'profile/public.jsp': 'Perfil público: reputación, publicaciones, reseñas.',
 V + 'cart/index.jsp': 'Carrito agrupado por publicante. Mirá la URL de la tapa (línea 53).',
 V + 'error/400.jsp': 'Pedido inválido.', V + 'error/403.jsp': 'Sin permiso.',
 V + 'error/404.jsp': 'No encontrado.', V + 'error/409.jsp': 'Conflicto: el estado cambió.',
 G + 'head.tag': 'Cabecera HTML común: estilos y scripts.',
 G + 'site-header.tag': 'Barra superior: marca, buscador, acciones, aviso de verificación.',
 G + 'brand.tag': 'Marca.', G + 'back-link.tag': 'Enlace de volver.',
 G + 'h1.tag': 'Título.', G + 'h3.tag': 'Subtítulo con nivel configurable.', G + 'p.tag': 'Párrafo.',
 G + 'span.tag': 'Texto en línea.', G + 'icon.tag': 'Iconos SVG de una lista cerrada.',
 G + 'button.tag': 'Botón o enlace con variantes.',
 G + 'text-input.tag': 'Campo ligado a un form con etiqueta, pista y error.',
 G + 'input-control.tag': 'Input sin ligar, con soporte de sugerencias.',
 G + 'textarea.tag': 'Área de texto ligada.', G + 'select.tag': 'Select ligado.',
 G + 'select-control.tag': 'Select sin ligar.', G + 'segmented-control.tag': 'Grupo de radios.',
 W + 'css/tokens.css': 'Variables de color, tipografía y espacio.',
 W + 'css/components.css': 'Estilos de los componentes.',
 W + 'css/style.css': 'Estilos por página. Largo: recorrelo por secciones.',
 W + 'images/logo.svg': 'Isotipo.',
 R + 'i18n/messages.properties': 'Por defecto, español.',
 R + 'i18n/messages_en.properties': 'Inglés.', R + 'i18n/messages_fr.properties': 'Francés.',
 R + 'i18n/messages_es.properties': 'Vacío a propósito.',
 'tools/paw_checks.py': 'Tres chequeos estáticos.', 'tools/git-hooks/pre-commit': 'Corre los chequeos antes del commit.',
 'docs/issues/observaciones-sprint-2/01-cuenta-verificada-busqueda-suggestions-autorizacion.md': 'Las cuatro observaciones de la cátedra y su resolución. Lectura obligada antes de la defensa.',
 'docs/issues/conversacion-consulta/01-conversacion-de-una-consulta.md': 'Diseño de la conversación.',
 'docs/specs/feature_venta-con-comprobante_20260924.md': 'Especificación de la venta.',
 'docs/plans/carrito-consultas.md': 'Plan del carrito.',
 'docs/plans/venta-con-comprobante.md': 'Plan de la venta. Muy largo: usalo como consulta.',
 'docs/plans/perfil-consultas-ui.md': 'Plan del rediseño de perfil y consultas. Muy largo.',
}
MAIL = {'welcome': 'Bienvenida.', 'email-verification': 'Enlace de verificación.', 'password-reset': 'Enlace de recuperación.',
        'password-changed': 'Aviso de cambio de contraseña.', 'post-interest': 'Consulta recibida.',
        'inquiry-update': 'Cambio de estado de una consulta.', 'inquiry-message': 'Mensaje nuevo.'}
